### ISSUE TITLE
Missing tclsh.exe

### ISSUE THREAD

**Issue by lamuzzachiodi** [aplsimple/alited#9] opened 2023-03-25 01:13 UTC
(Win7 32b - alited 1.4.3)

When i try to run a code , for example, i get this error (the path is right) :

```
couldn't execute "{C:\Program Files\Tcl86\bin\tclsh.exe}": no such file or directory
couldn't execute "{C:\Program Files\Tcl86\bin\tclsh.exe}": no such file or directory
    while executing
"open "|\"[Tclexe]\" $com""
    (procedure "alited::Run" line 10)
    invoked from within
"alited::Run [file join $::e_menu_dir e_menu.tcl] {*}$opts"
    (procedure "e_menu1" line 25)
    invoked from within
"e_menu1 $args"
    (procedure "e_menu" line 56)
    invoked from within
"e_menu {*}$opts tc=[alited::Tclexe]"
    (procedure "alited::tool::_run" line 40)
    invoked from within
"alited::tool::_run {} $in"
    (procedure "alited::run::Run" line 15)
    invoked from within
"alited::run::Run"
    invoked from within
".alwin.rundlg.fra.fra3.butRun invoke "
    invoked from within
".alwin.rundlg.fra.fra3.butRun instate !disabled { .alwin.rundlg.fra.fra3.butRun invoke } "
    invoked from within
".alwin.rundlg.fra.fra3.butRun instate pressed { .alwin.rundlg.fra.fra3.butRun state !pressed; .alwin.rundlg.fra.fra3.butRun instate !disabled { .alwin..."
    (command bound to event)
```

**Comment by aplsimple** [comment] 2023-03-25 15:03
Thanks for the feedback. 

The error will be fixed in v1.4.3.4 as soon as possible. It's caused by the spaces in the path to Tcl.

**Closed** 2023-04-27 15:45 UTC
